### ISSUE TITLE
Trainer ID too long

### ISSUE THREAD

**Issue by Nobodyofinterest70** [Admiral-Fish/PokeFinder#269] opened 2022-09-06 15:35 UTC
I'm trying to input my BDSP trainer id (850005) into the field in the profile manager but it doesn't fit, it only accepts 5 digits. Do I not need the entire TID to properly calculate the spread?

**Comment by Admiral-Fish** [comment] 2022-09-07 00:52
Duplicate of #255

See that issue for the explanation

**Closed by Admiral-Fish** 2022-09-07 00:52 UTC
