### ISSUE TITLE
BW2 Egg RNG seeds broken

### ISSUE THREAD

**Issue by NickPlayeZ** [Admiral-Fish/PokeFinder#295] opened 2023-05-08 19:42 UTC
Sometimes when I generate seeds for egg rng with my White 2 profile I get seeds that make sense and that RNG reporters Adjacent Seed Tool agrees happen under the given date/time/buttons but other times I get seeds shown which, according to adjacent seed tool, do not occur with that date/time/buttons. I've made screenshots of 4 examples where it did work (first 4) and 4 examples where it didnt work (last 4).
![1](https://user-images.githubusercontent.com/80699972/236917802-92c88f10-ff76-4776-9b5d-ac2204ef190b.PNG)
![2](https://user-images.githubusercontent.com/80699972/236917810-9d945560-158f-493c-859f-6622eacd05a1.PNG)
![3](https://user-images.githubusercontent.com/80699972/236917813-d3df3cae-1ddf-4c82-baff-02f91b73841d.PNG)
![4](https://user-images.githubusercontent.com/80699972/236917828-64f840d2-8455-4733-9d0f-bc3984a483ae.PNG)
![5](https://user-images.githubusercontent.com/80699972/236917907-d524157f-0ea6-47ad-80b5-2b26b5a4674d.PNG)
![6](https://user-images.githubusercontent.com/80699972/236917913-9c3dba77-96fb-460e-8da3-060d9b69e936.PNG)
![7](https://user-images.githubusercontent.com/80699972/236917919-210220b3-085d-48e3-abb2-766ee253e85a.PNG)
![8](https://user-images.githubusercontent.com/80699972/236917923-9fe104d4-62f6-441b-b454-705adffa7666.PNG)

**Comment by NickPlayeZ** [comment] 2023-05-11 17:40
Found another interesting example with the first and third of these marked seeds; neither of them actually happens with that date/time/buttons according to adjacent seed tool

![grafik](https://github.com/Admiral-Fish/PokeFinder/assets/80699972/8bb0e39f-9779-4b15-9853-d6b9f13af475)

**Comment by Admiral-Fish** [comment] 2023-05-28 10:26
I don't care about comparing to RNG reporter. Do these seeds not work in game?

**Comment by NickPlayeZ** [comment] 2023-05-29 13:50
no they don't what rng reporters adjacent seed tool shows is always exactly the seeds that I actually got

**Comment by NickPlayeZ** [comment] 2023-05-29 17:58
Pokefinders Calibration agrees with the seeds from adjacent seed tool as well
![grafik](https://github.com/Admiral-Fish/PokeFinder/assets/80699972/b5f39a5a-805f-4b8d-9474-94e075bcdb76)

**Comment by NickPlayeZ** [comment] 2023-05-29 18:27
Another piece of evidence: a Skorupi I just RNGd with that date/time/buttons. And as you can see in the second picture the by Pokefinder provided seed does not have these IVs anywhere near frame 0.


![grafik](https://github.com/Admiral-Fish/PokeFinder/assets/80699972/172f679b-dae9-43aa-bfa0-c25ee299e622)
![grafik](https://github.com/Admiral-Fish/PokeFinder/assets/80699972/0426c227-411a-43d2-916b-857a6ada908c)

**Comment by Admiral-Fish** [comment] 2023-06-10 01:27
Are you trying to calibrate eggs using wild pokemon settings in rng reporter? I can't imagine that working since inheritance

**Comment by Real96** [comment] 2023-06-10 15:21
> Are you trying to calibrate eggs using wild pokemon settings in rng reporter? I can't imagine that working since inheritance
> 
> BW2 eggs don't even generate IVs from MT

The problem exists. These are the proofs:
![image](https://github.com/Admiral-Fish/PokeFinder/assets/20956021/42faddfc-7bb9-4ee5-8ce5-51e3e6e0a4c6)

![image](https://github.com/Admiral-Fish/PokeFinder/assets/20956021/f848ae54-3cd9-43af-a137-d6342f1f6be4)

**Comment by Real96** [comment] 2023-06-10 17:11
Seems like the problem is another one, there may be a problem with threads. In the following images i just clicked the Search button many times, without changing the research parameters. The results are all different and all init seeds are wrong, theu don't match the showed date:

![image](https://github.com/Admiral-Fish/PokeFinder/assets/20956021/b34ad060-dd54-4f63-8d8e-3346a8321ed0)

![image](https://github.com/Admiral-Fish/PokeFinder/assets/20956021/2bc7b902-9704-493e-83cd-defe9b23af9b)

![image](https://github.com/Admiral-Fish/PokeFinder/assets/20956021/e1de78e4-b43c-4f55-af1f-4f18d3643f6b)

If you instead let the app generate the spreads without filtering, the init seeds are all correct

**Comment by Real96** [comment] 2023-06-10 17:43
Closing because the issue is not related to breeding generation, as showed in issu #304

**Closed by Real96** 2023-06-10 17:43 UTC
