### ISSUE TITLE
Gen 8 TID issue

### ISSUE THREAD

**Issue by Shdannn** [Admiral-Fish/PokeFinder#285] opened 2023-01-09 08:01 UTC
The character limit for a trainer ID in gen 8 is five but mine consists of six characters. (I triple checked using pkHex) could you possibly expand the character limit so that I can generate accurate results? For reference, my TID is: 101620. The section is shining pearl

**Comment by Admiral-Fish** [comment] 2023-01-09 14:42
Duplicate of https://github.com/Admiral-Fish/PokeFinder/issues/255

See that issue for the explanation

**Closed by Admiral-Fish** 2023-01-09 14:42 UTC
