### ISSUE TITLE
Add support for entering all possible TID values for Gen 8 in profiles

### ISSUE THREAD

**Issue by aliclubb** [Admiral-Fish/PokeFinder#290] opened 2023-04-20 14:54 UTC
TID values can be up to 999999 from Gen 7 onwards, instead of only up to 65535. I cannot enter my TID for Gen 8 under profiles as it's a 6 digit TID.

**Comment by SteveCookTU** [comment] 2023-04-20 15:27
Duplicate of #255

**Closed by SteveCookTU** 2023-04-20 15:27 UTC
