### ISSUE TITLE
Gen 3 Egg Inheritance is wrong

### ISSUE THREAD

**Issue by notblisy** [Admiral-Fish/PokeFinder#203] opened 2021-11-08 18:14 UTC
If you check show inheritance it will show all 6 stats as being inherited from parent A or B, when in only 3 total stats from the parents combined should be shown. Makes figuring out which parent to put in what spot, and what IV to catch the parents as difficult.

**Comment by Real96** [comment] 2021-11-15 13:00
Duplicate of #151 and fixed in d892099. Download [last commit](https://ci.appveyor.com/project/Admiral-Fish/pokefinder/builds/41528854)

**Closed by Real96** 2021-11-15 13:00 UTC
