### ISSUE TITLE
[Colo] GC Seed finder crashes on 4.0.0 release

### ISSUE THREAD

**Issue by hadecake** [Admiral-Fish/PokeFinder#272] opened 2022-10-10 06:26 UTC
Using the colo.precalc file, version 4.0.0 crashes when entering the second team. 
Tested 3.0.1 with the same file and it works just fine. 
Have not checked XD.
It would also be useful to add a link to find the precalcs inside the "would you like to use a precalc file" dialogue popup.
I am aware the files are no longer needed but it is still much faster when going through the seed finding process multiple times.

**Comment by Admiral-Fish** [comment] 2022-10-11 04:55
Duplicate of #239

**Closed by Admiral-Fish** 2022-10-11 04:55 UTC
