### ISSUE TITLE
Gen 4 Egg Search Yields Incorrect Ranges

### ISSUE THREAD

**Issue by greenDarkness** [Admiral-Fish/PokeFinder#118] opened 2020-08-31 22:52 UTC
Since at least commit 0a48cc0565c8be47f3b9254398478dc5cb2e63f1 searching for a seed which has a "PID Advance" with an min and max both set to 0 will yield no results found. 

If you set the search criteria to 0-1 then you will get results with 0s. Unsure if you will get 1s- I haven't seen any in 3 broad ranged search attempts. 

Searching ranges 4-5 yielded results ranging from 4-8.

This also applies to Advance searches. Seaching for Advance 13-13 yields Advance 15-25.

**Comment by Admiral-Fish** [comment] 2020-10-05 01:27
This is intended behavior. For example with 4-5, you are telling Pokefinder I want to start searching from advance 4 and look through up to 5 advances from there. This would give you advances 4-9. You are correct however in it only giving 4-8, which is fixed by a11f2df

This is how the other windows operate if you look at Stationary/Wild/etc. It's just that for egg I put the text boxes side by side instead of each other.

**Closed by Admiral-Fish** 2020-10-05 01:27 UTC
Labels: bug
