### ISSUE TITLE
TID should accept up to 6 digits

### ISSUE THREAD

**Issue by ygormsantos** [Admiral-Fish/PokeFinder#328] opened 2023-08-15 10:47 UTC
Currently, I'm only able to input 5 digits, not covering gen 8 TIDs
![Screenshot 2023-08-15 at 07 45 06](https://github.com/Admiral-Fish/PokeFinder/assets/115537873/4f64437c-d7ef-463f-8c9b-d501f9239090)

**Comment by SteveCookTU** [comment] 2023-08-15 13:22
Duplicate of #255 

See the linked issue for an explanation of Gen 8 IDs

**Closed** 2023-08-15 13:23 UTC
