### ISSUE TITLE
[Suggestion] Gen3 - Uknown Calculation

### ISSUE THREAD

**Issue by soaresden** [Admiral-Fish/PokeFinder#162] opened 2021-06-24 10:34 UTC
Hi ! 

Since I would like to generate a Uknown, I use the export to csv to calculate myself the Letter wanted on Excel

![image](https://user-images.githubusercontent.com/54243866/123248699-82fc3500-d4e8-11eb-953d-09ae674354c4.png)

I think it should be great to have it in the filter area ?

exemple : 

from PID : D3C5AA89
* converted in bin : 110100**11** 110001**01** 101010**10** 100010**01**
*getting last values and concatenate 11011001
*converted in dec = 217
* mod : 217/28 = 21
* 21 is letter V (A for 0, B for 1 .... Z for 25, ! for 26 and ? for 27)

**Comment by Admiral-Fish** [comment] 2021-06-27 20:28
Duplicate of #100

**Closed by Admiral-Fish** 2021-06-27 20:28 UTC
