### ISSUE TITLE
Gen 8 TID

### ISSUE THREAD

**Issue by KMNull** [Admiral-Fish/PokeFinder#274] opened 2022-10-17 09:56 UTC
On the windows version of this, the gen 8 TID (trainer id) is up to 6 character where as lower than gen 7 is up to 5  however on the app on profiles the TID can only go up to 5 characters.

**Comment by Admiral-Fish** [comment] 2022-10-19 01:06
Duplicate of #255

See that issue for the explanation

**Closed by Admiral-Fish** 2022-10-19 01:06 UTC
