### ISSUE TITLE
[GEN4] J/K static encounters synch lead bug on generator

### ISSUE THREAD

**Issue by cervizzz** [Admiral-Fish/PokeFinder#234] opened 2022-02-19 18:26 UTC
Synchronize lead not displaying properly for static encounters (J and K) on the generator. Most natures behave like a male cute charm lead, hardy synch doesn't do anything, brave even changes chatot cries. Tested on version 4.0.0.

**Comment by Admiral-Fish** [comment] 2022-02-19 21:52
Duplicate of #232

**Closed by Admiral-Fish** 2022-02-19 21:52 UTC
