### ISSUE TITLE
App keeps quitting unexpectedly 

### ISSUE THREAD

**Issue by Ravage95** [Admiral-Fish/PokeFinder#256] opened 2022-06-25 20:45 UTC
I use a Mac OS laptop and am trying to find seeds for Pokemon Colosseum with PokeFinder. But every time I'm in the middle of finding the seed, Pokefinder keeps on quitting unexpectedly. 

Is there any particular reason why it keeps doing that?

**Comment by Admiral-Fish** [comment] 2022-06-26 01:46
Duplicate of #239

Use latest build from appveyor

**Closed by Admiral-Fish** 2022-06-26 01:46 UTC
